name: 'Reset Staging'
description: 'Reset the staging branch with the main branch merging some branches identified by a specific label.'
inputs:
  repository:
    description: 'The repository name in Github owner/repository. e.g: TheMenu/monrepo'
    default: ${{ github.repository }}
  source-branch:
    description: 'The branch name used as base branch to synchronize the target one.'
    default: 'main'
  target-branch:
    description: 'The branch name used as target.'
    default: 'staging'
  label:
    description: 'The PR label that is used to find branch to merge in the target one.'
    default: 'staging'
  user-name:
    description: 'The user name used to push the branch.'
    default: 'github-actions[bot]'
  user-email:
    description: 'The user email used to push the branch.'
    default: 'github-actions[bot]@users.noreply.github.com'

branding:
  color: 'blue'
  icon: 'git-merge'

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - run: |
        git config user.name "${{ inputs.user-name }}"
        git config user.email "${{ inputs.user-email }}"
        bun ${{ github.action_path }}/index.ts \
          --repository ${{ inputs.repository }} \
          --source-branch ${{ inputs.source-branch }} \
          --target-branch ${{ inputs.target-branch }} \
          --label ${{ inputs.label }}
      shell: bash
