name: Reset Staging

on:
  workflow_dispatch:

jobs:
  reset-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Reset Staging Action
        uses: ./
        with:
          repository: ${{ github.repository }}
          source-branch: 'main'
          target-branch: 'staging'
          label: 'staging'
          user-name: 'github-actions[bot]'
          user-email: 'github-actions[bot]@users.noreply.github.com'
